### ISSUE TITLE
Handle feed name in the view when there is no channel name

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/iihs_curation_dashboard#238]

**Comment by salus-sage** [comment]
But right now, no channel name means u route to dashboard route? U show
only recent feeds in all channels? And channel grid?
Then in background fetch rest of the channels.
Makes sense?

On Apr 26, 2018 7:45 AM, "vaishnavisv" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/janastu/iihs_curation_dashboard/issues/238>, or mute
the thread
