### ISSUE TITLE
Media monitor icon in the sidebar

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/iihs_curation_dashboard#239]

**Comment by salus-sage** [comment]
This means icon AND group name right?

On Apr 26, 2018 6:13 PM, "vaishnavisv" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/janastu/iihs_curation_dashboard/issues/239>, or mute
the thread

**Comment by vaishnavisv** [comment]
Ya icon and group name
