### ISSUE TITLE
Merging of Boards in Archived view

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#274]
In today’s curation, after publishing all the boards, I was reviewing the items and noticed that one category Urban Transport was not showing. I went to the board to check if it was published, and it was. Then I went back to the published view and saw that Urban Transport had merged with Urban Health for some reason. Related to the issue above, to try to separate Transport and Health, I checked to see if I can republish the Health board. I was able to republish the board, and the news items in the Archive view got duplicated in this board. However, the boards did not separate. The boards got separated when I tried republishing the Transport board again. 
![health board](https://user-images.githubusercontent.com/38202501/40239595-1c37451c-5ad4-11e8-9e35-f41d7890b618.JPG)

**Comment by salus-sage** [comment]
Can you please explain further what you did in the application, when you
say re-publish?

**Comment by salus-sage** [comment]
Hi,

I'm following up on this issue, can you please provide more details on which feed exactly with titles or example. 
As you can see from the screenshots below, i'm not able to understand what is merge? and re-publish? because we do not have such features. 
![screenshot 13](https://user-images.githubusercontent.com/6399323/40352121-b37b7296-5dcb-11e8-8d65-9d26b68f0f53.png)
![screenshot 11](https://user-images.githubusercontent.com/6399323/40352124-b48009c2-5dcb-11e8-8fc4-1c8d26cd55ac.png)
![screenshot 12](https://user-images.githubusercontent.com/6399323/40352126-b4d14a58-5dcb-11e8-86d6-4185683e36c4.png)

**Comment by vaishnavisv** [comment]
Resolved hence closing
