### ISSUE TITLE
publish page lifecycle and controls - enhancement requested

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#275]
## Following up on the issue, where we were getting a blank page after publishing one category

now we are getting the particular published category on that page. Is there a way in which we can be redirected back to the home page containing the boards and the feeds so that we can continue publishing the remaining category without clicking the back button every time.

**Comment by salus-sage** [comment]
1. where we were getting a blank page after publishing one category
Answer: This issue is now resolved, you should be getting the content in the published page

2. Is there a way in which we can be redirected back to the home page containing the boards and the feeds
Answer: At this time we see this publish page as a interface, where the curator is allowed to do Mark all (Ctrl-A) and Copy(Ctrl-C) so, we have kept minimum interfaces here, which might conflict with the copy-paste workflow. 

However, what we can do is to open the publish page in a newtab. 
@vaishnavisv _target for the publish page?

**Comment by salus-sage** [comment]
I guess it's a nice practice to have the navigation explicit, without any
assumption of user habits.
We can I stead open the published page in a new tab,
We ll let u knw when the changes are made live on server.

**Comment by vaishnavisv** [comment]
New tab for Publish page and Archives page is now made live on server
